<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="../maincontent.css" rel="stylesheet" type="text/css" />
<link href="../../styles.css" rel="stylesheet" type="text/css" />
<link href="../../sidemenu.css" rel="stylesheet" type="text/css" />
<script src="SpryAssets/SpryTabbedPanels.js" type="text/javascript"></script>
<script src="SpryAssets/SpryAccordion.js" type="text/javascript"></script>
<link href="SpryAssets/SpryTabbedPanels.css" rel="stylesheet" type="text/css" />
<link href="SpryAssets/SpryAccordion.css" rel="stylesheet" type="text/css" />

</head>

<body>
<%
    if((session.getAttribute("loginEmail"))!=null&&(session.getAttribute("loginPass")!=null))
    {
    %>
<jsp:include page="../../header1.jsp" flush="false"></jsp:include>
<%
    }
    else
    {
    %>
<jsp:include page="../../header2.jsp" flush="false"></jsp:include>
<%
     }
    %>
<jsp:include page="../../sidemenu.html" flush="false"></jsp:include>
<div id="main_contnt">
  <div id="TabbedPanels1" class="TabbedPanels">
    <ul class="TabbedPanelsTabGroup">
      <li class="TabbedPanelsTab" tabindex="1">About</li>
      <li class="TabbedPanelsTab" tabindex="1">Winter</li>
      <li class="TabbedPanelsTab" tabindex="1">Summer</li>
    </ul>
    <div class="TabbedPanelsContentGroup">
      <div class="TabbedPanelsContent">Indian          subcontinent plays host to a number of migratory birds in summers as          well as winters. It is estimated that over hundred species of migratory          birds fly to India, either in search of feeding grounds or to escape the          severe winter of their native habitat. The numerous wildlife sanctuaries          set up in the country serve as their temporary habitat. Bird lovers from          all over the country visit these sanctuaries to get a glimpse of some of          the rarest species of birds in the world. The beauty of the birds,          combined with the splendor of the natural environment provides the          perfect setting for a nature lover.<br />
        <br />
Usually, birds start migrating towards other areas when they perceive          the tailwind to be favorable. However, once they start their migration          journey, nothing can stop them, except extremely bad weather. Many birds          prefer to fly at a higher altitude while migrating. This is because          winds usually prevail at higher altitudes and at the same time, the cold          temperature at these altitudes helps them in diffusing the body heat,          which is generated by their flight muscles. The timing of the migration          is usually a mixture of internal and external stimulus. <br />
<br />
<img src="deccon_indian-migratory-birds.jpg" alt="Indian Migratory Birds" align="right" height="155" width="205" /> Migrating birds start on a journey when they feel that they have put on          enough fat to provide them energy throughout the journey. Then, the          tendency to aggregate into flocks is another determinant of the time of          migration. Even after the flock, which has to fly together, has          gathered, the birds keep on feeding till the weather conditions become          favorable. Thus, apart from the internal clock of the birds and their          flock, it is also the availability of food and the weather conditions          that play a role in the determination of the time of migration.<br />
      </div>
      <div class="TabbedPanelsContent">
        <div><strong>Migratory Birds Coming to India in Winter Season</strong></div>
        <ul>
          <li>Siberian Cranes</li>
          <li>Greater Flamingo</li>
          <li>Ruff</li>
          <li>Black winged Stilt</li>
          <li>Common Teal</li>
          <li>Common Greenshank</li>
          <li>Northern Pintail</li>
          <li>Yellow Wagtail</li>
          <li>White Wagtail</li>
          <li>Northern Shoveler</li>
          <li>Rosy Pelican</li>
          <li>Gadwall</li>
          <li>Wood Sandpiper</li>
          <li>Spotted Sandpiper</li>
          <li>Eurasian Wigeon</li>
          <li>Black tailed Godwit</li>
          <li>Spotted Redshank</li>
          <li>Starling</li>
          <li>Bluethroat </li>
          <li>Long billed Pipit</li>
        </ul>
      </div>
      <div class="TabbedPanelsContent">
        <div><strong>Migratory Birds Coming to India in Summer Season</strong></div>
        <ul>
          <li>Asian Koel</li>
          <li>Black crowned Night Heron</li>
          <li>Eurasian Golden Oriole</li>
          <li>Comb Duck</li>
          <li>Blue-cheeked Bee Eater</li>
          <li>Blue-tailed Bee-Eater </li>
          <li>Cuckoos </li>
        </ul>
      </div>
    </div>
  </div>
<script type="text/javascript">
var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
</script>
</body>
</html>
